name: Build and Distribute APK via App Center

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

    - name: Run flutter doctor
      run: flutter doctor

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Install App Center CLI
      run: npm install -g appcenter-cli

    - name: Login to App Center
      run: appcenter login --token ${{ secrets.APPCENTER_API_TOKEN }}

    - name: Distribute APK via App Center
      run: |
        appcenter distribute release \
          --app "yosrawanene28/verdai" \
          --group "Collaborators" \
          --file "build/app/outputs/flutter-apk/app-release.apk" \
          --release-notes "Automated build from GitHub Actions"
      env:
        APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
