name: Build and Send APK via Email

on:
  push:
    branches:
      - develop

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

    - name: Run flutter doctor
      run: flutter doctor

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Check network connectivity to SMTP server
      run: |
        ping -c 4 smtp.office365.com

    - name: Send APK via Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "New APK Build"
        body: "Please find the attached APK build."
        to: "yasmina.tounseya@gmail.com"
        from: ${{ secrets.EMAIL_USERNAME }}
        secure: true  
        attachments: "build/app/outputs/flutter-apk/app-release.apk"
