name: Build and Release APK

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

    - name: Run flutter doctor
      run: flutter doctor

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK to App Center
      env:
        APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}  # Reference to the secret stored in GitHub
      run: |
        curl \
          -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
          -F "release_notes=Automated build from GitHub Actions" \
          -F "distribution_group_names=Collaborators" \  # Replace with your distribution group
          -F "mandatory_update=true" \  # Optional: Mark the update as mandatory
          -H "X-API-Token: $APPCENTER_API_TOKEN" \
          https://api.appcenter.ms/v0.1/apps/{yosra-wan}/{verdai}/release_uploads  # Replace with your App Center owner and app name
